name: Build Godot Project

on:
  push:
    branches:
      - dev
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  REPO_NAME: DmitriySkiba/Jump-Fight


jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with:
          ref: dev

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.*'

      - name: Godot Setup
        uses: lihop/godot-setup@v2.1.2
        with:
          version: 4.2.1-stable
          bits: 64
          mono: true
          alias: godot
          export-templates: true

      - name: Project build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: Jump-Fight
          preset: windows
          subdirectory: build

      - name: Refactor
        run: |
          tree
          pwd
          sudo cp ./build/build/Jump-Fight ./build/Jump-Fight.exe

      - name: Create tag        
        run: |        
          git tag -a mytag -m "Automatically generated tag"     

      - name: Install gh-release action
        uses: softprops/action-gh-release@v1

      - name: Upload file to release
        run: |
         gh release create ${{ env.REPO_NAME }} "${tag}" ./build/Jump-Fight.exe --assets Jump-Fight.exe
