name: Build Godot Project

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Godot Setup
        uses: lihop/godot-setup@v2.1.2
        with:
          # Godot version to use
          version: 4.2.1-stable
          bits: 64
          mono: true
          alias: godot
          export-templates: true
          
      - name: Project build
        run: |
          v4.2.1-stable/Godot_v4.2.1-stable_mono_linux_x86_64/Godot_v4.2.1-stable_mono_linux.x86_64 --export-release --headless "Windows Desktop" build/Jump-Fight.exe

