name: Build C# Project

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Install Godot
        run: |
          wget "https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.arm64.zip"
          wget "https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz"
          unzip Godot_v4.2.1-stable_linux.arm64.zip
          mkdir release
          Godot_v4.2.1-stable_linux.arm64 --export-release ./Godot_v4.2.1-stable_export_templates.tpz release
          tree
