name: Build Godot Project

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  REPO_NAME: DmitriySkiba/Jump-Fight


jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Mono
        uses: actions/setup-mono@v2
        with:
          mono-version: '6.x' # Adjust the version as needed

      - name: Godot Setup
        uses: lihop/godot-setup@v2.1.2
        with:
          version: 4.2.1-stable
          bits: 64
          mono: true
          alias: godot
          export-templates: true

      - name: Project build
        run: |
          godot --export "Windows Desktop" ./build/Jump-Fight.exe

      - name: Refactor
        run: |
          tree
          pwd
          sudo cp ./build/build/Jump-Fight ./build/Jump-Fight.exe

      - name: Generate Git Tag
        id: generate_tag
        run: |
           VERSION_PREFIX="v"
           VERSION_MAJOR_MINOR="1.0"
           VERSION_PATCH="0"
           
           NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
           echo "Generated new tag: $NEW_TAG"
           echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

        

    #  - name: Create Tag
    #    uses: negz/create-tag@v1
    #    with:
    #      version: v1.0.0
    #      token: ${{ secrets.GITHUB_TOKEN }}


      - name: Install gh-release action
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/Jump-Fight.exe
          tag_name: $NEW_TAG
        
      #- name: Upload file to release
       # run: |
        # gh release create ${{ env.REPO_NAME }} "${tag}" ./build/Jump-Fight.exe --assets Jump-Fight.exe
