name: Build Godot

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Export Game
       uses: firebelley/godot-export@v5.2.1
       with:
          godot_executable_download_url: https:///downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_linux_x86_64.zip
          godot_export_templates_downloads_url: https:///downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_export_templates.tpz
          relative_project_path: ./
          create_release: true
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
